[dependencies]
base = "0.11.2"
map = "9.0.1"
uuid = "1.0.0"
stableheapbtreemap = "1.5.0"
icrc7-mo = "0.4.1"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc3-mo = "0.2.6"
icrc37-mo = "0.4.2"
vector = "0.4.0"