export const foodData = [
    { name: 'Chicken Biryani', calories: 190, carbohydrates: 25, protein: 10, fat: 5 },
    { name: 'Mutton Rogan Josh', calories: 180, carbohydrates: 5, protein: 14, fat: 12 },
    { name: 'Tandoori Chicken', calories: 160, carbohydrates: 2, protein: 11, fat: 10 },
    { name: 'Prawn Masala', calories: 140, carbohydrates: 3, protein: 10, fat: 9 },
    { name: 'Bread Omelette', calories: 220, carbohydrates: 20, protein: 11, fat: 12 },
    { name: 'Egg Fried Rice', calories: 160, carbohydrates: 22, protein: 7, fat: 7 },
    { name: 'Egg Noodles', calories: 150, carbohydrates: 23, protein: 6, fat: 6 },
    { name: 'Egg Puffs', calories: 250, carbohydrates: 28, protein: 8, fat: 14 },
    { name: 'Boiled Egg', calories: 77, carbohydrates: 0.6, protein: 7, fat: 5 },
    { name: 'Chicken Breast Boiled', calories: 165, carbohydrates: 0, protein: 31, fat: 4 },
    { name: 'Scrambled Egg', calories: 91, carbohydrates: 1, protein: 6, fat: 7 },
    { name: 'Fried Egg', calories: 92, carbohydrates: 1, protein: 6, fat: 7 },
    { name: 'Omelette', calories: 94, carbohydrates: 1, protein: 6, fat: 7 },
    { name: 'Egg Curry', calories: 120, carbohydrates: 3, protein: 8, fat: 9 },
    { name: 'Egg Bhurji', calories: 101, carbohydrates: 2, protein: 7, fat: 8 },
    { name: 'Deviled Egg', calories: 64, carbohydrates: 1, protein: 6, fat: 4.5 },
    { name: 'Egg Sandwich', calories: 250, carbohydrates: 28, protein: 10, fat: 12 },
    { name: 'Egg Salad', calories: 210, carbohydrates: 4, protein: 9, fat: 18 },
    { name: 'Egg Drop Soup', calories: 70, carbohydrates: 1, protein: 6, fat: 4 },
    { name: 'Chole Bhature', calories: 300, carbohydrates: 35, protein: 10, fat: 15 },
    { name: 'Vegetable Biryani', calories: 200, carbohydrates: 28, protein: 5, fat: 8 },
    { name: 'Dal Makhani', calories: 150, carbohydrates: 22, protein: 9, fat: 6 },
    { name: 'Aloo Gobi', calories: 120, carbohydrates: 15, protein: 4, fat: 8 },
    { name: 'Baingan Bharta', calories: 110, carbohydrates: 10, protein: 3, fat: 6 },
    { name: 'Palak Paneer', calories: 180, carbohydrates: 10, protein: 8, fat: 12 },
    { name: 'Rajma', calories: 140, carbohydrates: 25, protein: 7, fat: 4 },
    { name: 'Masala Dosa', calories: 165, carbohydrates: 30, protein: 4, fat: 6 },
    { name: 'Vegetable Pulao', calories: 130, carbohydrates: 25, protein: 4, fat: 5 },
    { name: 'Matar Paneer', calories: 190, carbohydrates: 12, protein: 10, fat: 12 },
    { name: 'Stuffed Paratha', calories: 250, carbohydrates: 35, protein: 8, fat: 10 },
    { name: 'Kofta', calories: 220, carbohydrates: 18, protein: 7, fat: 14 },
    { name: 'Bhindi Masala', calories: 110, carbohydrates: 12, protein: 3, fat: 6 },
    { name: 'Chicken Korma', calories: 240, carbohydrates: 8, protein: 15, fat: 16 },
    { name: 'Goan Fish Curry', calories: 200, carbohydrates: 6, protein: 12, fat: 12 },
    { name: 'Gajar Ka Halwa', calories: 150, carbohydrates: 25, protein: 3, fat: 8 },
    { name: 'Malpua', calories: 300, carbohydrates: 45, protein: 4, fat: 12 },
    { name: 'Seviyan Kheer', calories: 130, carbohydrates: 20, protein: 4, fat: 4 },
    { name: 'Paneer Tikka', calories: 150, carbohydrates: 6, protein: 10, fat: 10 },
    { name: 'Methi Malai Matar', calories: 180, carbohydrates: 12, protein: 5, fat: 12 },
    { name: 'Kadhi Pakora', calories: 100, carbohydrates: 12, protein: 4, fat: 6 },
    { name: 'Chicken Sandwich', calories: 675, carbohydrates: 60, protein: 42, fat: 30 },
    { name: 'Ham Sandwich', calories: 525, carbohydrates: 45, protein: 30, fat: 23 },
    { name: 'Veggie Sandwich', calories: 450, carbohydrates: 75, protein: 15, fat: 12 },
    { name: 'Turkey Sandwich', calories: 600, carbohydrates: 53, protein: 38, fat: 27 },
    { name: 'Tuna Sandwich', calories: 570, carbohydrates: 45, protein: 33, fat: 24 },
    { name: 'Egg Salad Sandwich', calories: 480, carbohydrates: 42, protein: 21, fat: 27 },
    { name: 'BLT Sandwich', calories: 600, carbohydrates: 53, protein: 27, fat: 33 },
    { name: 'Grilled Cheese Sandwich', calories: 450, carbohydrates: 42, protein: 18, fat: 24 },
    { name: 'Roast Beef Sandwich', calories: 630, carbohydrates: 48, protein: 39, fat: 30 },
    { name: 'Pulled Pork Sandwich', calories: 720, carbohydrates: 75, protein: 36, fat: 30 },
    { name: 'Roti', calories: 264, carbohydrates: 57, protein: 9, fat: 3 },
    { name: 'Chicken Curry', calories: 151, carbohydrates: 6, protein: 17, fat: 8 },
    { name: 'Samosa', calories: 262, carbohydrates: 31, protein: 5, fat: 13 },
    { name: 'Dosa', calories: 168, carbohydrates: 28, protein: 4, fat: 4 },
    { name: 'Paneer Butter Masala', calories: 292, carbohydrates: 11, protein: 12, fat: 23 },
    { name: 'Rice (white)', calories: 130, carbohydrates: 28, protein: 3, fat: 0 },
    { name: 'Dal (lentils)', calories: 116, carbohydrates: 20, protein: 9, fat: 0 },
    { name: 'Rajma (kidney beans)', calories: 127, carbohydrates: 22, protein: 9, fat: 1 },
    { name: 'Bhindi (Okra)', calories: 33, carbohydrates: 7, protein: 2, fat: 0 },
    { name: 'Idli', calories: 128, carbohydrates: 27, protein: 3, fat: 0 },
    { name: 'Biryani', calories: 215, carbohydrates: 28, protein: 7, fat: 8 },
    { name: 'Butter Chicken', calories: 140, carbohydrates: 5, protein: 20, fat: 11 },
    { name: 'Chole (Chickpeas)', calories: 164, carbohydrates: 27, protein: 9, fat: 5 },
    { name: 'Poha', calories: 130, carbohydrates: 20, protein: 2, fat: 3 },
    { name: 'Rasgulla', calories: 186, carbohydrates: 38, protein: 4, fat: 1 },
    { name: 'Aloo Paratha', calories: 204, carbohydrates: 28, protein: 4, fat: 8 },
    { name: 'Upma', calories: 154, carbohydrates: 24, protein: 5, fat: 3 },
    { name: 'Puri', calories: 274, carbohydrates: 36, protein: 4, fat: 11 },
    { name: 'Kheer (Rice Pudding)', calories: 150, carbohydrates: 22, protein: 3, fat: 5 },
    { name: 'Vada', calories: 287, carbohydrates: 32, protein: 6, fat: 14 },
    { name: 'Gulab Jamun', calories: 432, carbohydrates: 71, protein: 6, fat: 14 },
    { name: 'Pulao', calories: 174, carbohydrates: 23, protein: 3, fat: 7 },
    { name: 'Fish Curry', calories: 142, carbohydrates: 3, protein: 16, fat: 7 },
    { name: 'Misal Pav', calories: 208, carbohydrates: 28, protein: 8, fat: 7 },
    { name: 'Kachori', calories: 272, carbohydrates: 36, protein: 6, fat: 12 },
    { name: 'Jalebi', calories: 300, carbohydrates: 62, protein: 2, fat: 5 },
    { name: 'Papad', calories: 371, carbohydrates: 58, protein: 18, fat: 1 },
    { name: 'Pav Bhaji', calories: 196, carbohydrates: 24, protein: 5, fat: 8 },
    { name: 'Pakora', calories: 260, carbohydrates: 25, protein: 5, fat: 14 },
    { name: 'Sabudana Khichdi', calories: 204, carbohydrates: 45, protein: 2, fat: 1 },
    { name: 'Seviyan (Vermicelli)', calories: 165, carbohydrates: 28, protein: 5, fat: 3 },
    { name: 'Dhokla', calories: 163, carbohydrates: 18, protein: 7, fat: 6 },
    { name: 'Pesarattu (Green Gram)', calories: 160, carbohydrates: 29, protein: 9, fat: 1 },
    { name: 'Mutton Biryani', calories: 204, carbohydrates: 24, protein: 8, fat: 8 },
    { name: 'Bhatura', calories: 307, carbohydrates: 46, protein: 7, fat: 11 },
    { name: 'Kesari Bath', calories: 195, carbohydrates: 32, protein: 2, fat: 6 },
    { name: 'Mysore Pak', calories: 466, carbohydrates: 59, protein: 8, fat: 22 },
    { name: 'Milk', calories: 65, carbohydrates: 5, protein: 3, fat: 4 },
    { name: 'Butter', calories: 740, carbohydrates: 0, protein: 0, fat: 82 },
    { name: 'Cream', calories: 210, carbohydrates: 3, protein: 2, fat: 21 },
    { name: 'Cheese', calories: 310, carbohydrates: 1, protein: 22, fat: 25 },
    { name: 'Ice Cream', calories: 170, carbohydrates: 25, protein: 4, fat: 7 },
    { name: 'Margarine', calories: 740, carbohydrates: 1, protein: 0, fat: 81 },
    { name: 'Egg Salad Sandwich', calories: 480, carbohydrates: 42, protein: 21, fat: 27 },
    { name: 'BLT Sandwich', calories: 600, carbohydrates: 53, protein: 27, fat: 33 },
    { name: 'Grilled Cheese Sandwich', calories: 450, carbohydrates: 42, protein: 18, fat: 24 },
    { name: 'Roast Beef Sandwich', calories: 630, carbohydrates: 48, protein: 39, fat: 30 },
    { name: 'Pulled Pork Sandwich', calories: 720, carbohydrates: 75, protein: 36, fat: 30 },
    { name: 'Chicken (Roast)', calories: 150, carbohydrates: 0, protein: 25, fat: 5 },
    { name: 'Fish (eg. Cod)', calories: 220, carbohydrates: 8, protein: 20, fat: 10 },
    { name: 'Beans (Boiled)', calories: 20, carbohydrates: 3, protein: 2, fat: 0 },
    { name: 'Cabbage (Boiled)', calories: 10, carbohydrates: 1, protein: 1, fat: 0 },
    { name: 'Carrot (Boiled)', calories: 20, carbohydrates: 4, protein: 0, fat: 0 },
    { name: 'Cauliflower (Boiled)', calories: 10, carbohydrates: 1, protein: 2, fat: 0 },
    { name: 'Cucumber (Raw)', calories: 10, carbohydrates: 2, protein: 1, fat: 0 },
    { name: 'Peas (Boiled)', calories: 50, carbohydrates: 8, protein: 5, fat: 0 },
    { name: 'Potatoes (Boiled)', calories: 80, carbohydrates: 22, protein: 1, fat: 0 },
    { name: 'Tomatoes', calories: 15, carbohydrates: 3, protein: 1, fat: 0 },
    { name: 'Apples', calories: 45, carbohydrates: 12, protein: 0, fat: 0 },
    { name: 'Bananas', calories: 80, carbohydrates: 20, protein: 1, fat: 0 },
    { name: 'Cherries', calories: 50, carbohydrates: 12, protein: 1, fat: 0 },
    { name: 'Grapes', calories: 60, carbohydrates: 15, protein: 1, fat: 0 },
    { name: 'Oranges', calories: 35, carbohydrates: 9, protein: 1, fat: 0 },
    { name: 'Pea Nuts (Roasted)', calories: 570, carbohydrates: 9, protein: 24, fat: 49 },
    { name: 'Bread', calories: 230, carbohydrates: 50, protein: 8, fat: 2 },
    { name: 'Rice (White Boiled)', calories: 120, carbohydrates: 30, protein: 2, fat: 0 },
    { name: 'Cornflakes with milk', calories: 205, carbohydrates: 35, protein: 7, fat: 4 },
    { name: 'Wheat Bran', calories: 200, carbohydrates: 23, protein: 14, fat: 6 },
    { name: 'Chicken Chettinad', calories: 210, carbohydrates: 8, protein: 15, fat: 14 },
    { name: 'Lamb Vindaloo', calories: 240, carbohydrates: 5, protein: 18, fat: 16 },
    { name: 'Keema Pav', calories: 250, carbohydrates: 20, protein: 12, fat: 15 },
    { name: 'Bisi Bele Bath', calories: 180, carbohydrates: 30, protein: 5, fat: 6 },
    { name: 'Undhiyu', calories: 200, carbohydrates: 25, protein: 4, fat: 10 },
    { name: 'Paneer Bhurji', calories: 220, carbohydrates: 6, protein: 10, fat: 16 },
    { name: 'Basundi', calories: 150, carbohydrates: 25, protein: 4, fat: 6 },
    { name: 'Patishapta', calories: 200, carbohydrates: 30, protein: 3, fat: 8 },
    { name: 'Moong Dal Halwa', calories: 330, carbohydrates: 40, protein: 6, fat: 14 }
];

  

  